---

definitions:
  installscript: &baseInstallDeps
    export DEBIAN_FRONTEND='noninteractive' ;
    export COMPOSER_ALLOW_SUPERUSER=1 ;
    IPADDRESS=$(grep "$HOSTNAME$" /etc/hosts | grep -Po '^\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}') ; export IPADDRESS ;
    apt-get -qq update &&
    mkdir -p /usr/share/man/man1 /usr/share/man/man3 /usr/share/man/man7 &&
    apt-get -qq install default-jre-headless postgresql-client mariadb-client &&
    curl -sS https://raw.githubusercontent.com/creationix/nvm/v0.38.0/install.sh | bash &&
    . ~/.bashrc &&
    nvm install -b --no-progress v14.15.0 &&
    curl -sS https://getcomposer.org/installer | php -- --install-dir='/usr/local/bin' --filename='composer' &&
    touch /usr/local/bin/phpenv && chmod +x /usr/local/bin/phpenv &&
    mkdir -pv /tmp/plugin ; cp -ru "${BITBUCKET_CLONE_DIR}"/* /tmp/plugin ; rm -rf "${BITBUCKET_CLONE_DIR:?}"/* ;
    mkdir -pv "${BITBUCKET_CLONE_DIR}/plugin" && cp -ru /tmp/plugin/* "${BITBUCKET_CLONE_DIR}"/plugin ;
    composer create-project -n --no-dev --no-progress --no-ansi --prefer-dist moodlehq/moodle-plugin-ci ci ^3 &&
    { [ "${MOODLE_START_BEHAT_SERVERS}" = '' ] && export MOODLE_START_BEHAT_SERVERS='NO' ; } ;
    { [ "${MOODLE_BEHAT_WWWROOT}" = '' ] && export MOODLE_BEHAT_WWWROOT="http://$IPADDRESS:8000" ; } ;
    { [ "${MOODLE_BEHAT_WDHOST}" = '' ] && export MOODLE_BEHAT_WDHOST="http://$IPADDRESS:4444/wd/hub" ; } ;
    { [ "${MOODLE_REPO}" = '' ] && export MOODLE_REPO='https://bitbucket.org/moodle/moodle.git' ; } ;
    { [ "${MOODLE_BRANCH}" = '' ] && export MOODLE_BRANCH='MOODLE_311_STABLE' ; } ;
    { [ "${DB}" = '' ] && export DB='mariadb' ; } ;
    { [ "${DB_USER}" = '' ] && export DB_USER='root' ; } ;
    { [ "${DB_PWD}" = '' ] && export DB_PWD='test' ; } ;
    export TRAVIS_BUILD_DIR="$BITBUCKET_CLONE_DIR/plugin" ;
    export PATH="$BITBUCKET_CLONE_DIR/ci/bin:$BITBUCKET_CLONE_DIR/ci/vendor/bin:$PATH" ;
  instscript: &baseInst
    moodle-plugin-ci install --no-ansi -n --db-type="$DB" --db-user="$DB_USER" --db-pass="$DB_PWD"
    --branch="$MOODLE_BRANCH" --db-host="127.0.0.1"
  behatscript: &baseBehat
    docker run -d -p 4444:4444 --shm-size=1g -v "$BITBUCKET_CLONE_DIR/moodle:$BITBUCKET_CLONE_DIR/moodle"
    "selenium/standalone-firefox:3" &&
    { php -S 0.0.0.0:8000 -t "$BITBUCKET_CLONE_DIR/moodle" > /dev/null 2>&1 & } ; sleep 10 ;
  steps:
    - step: &base
        image: moodlehq/moodle-php-apache:7.3
        name: "Moodle, PHP 7.3 and MariaDB"
        caches:
          - composer
          - npm
          - docker
        script:
          - *baseInstallDeps
          - *baseInst
          - *baseBehat
        services:
          - mariadb
          - docker
  services:
    mariadb:
      image: mariadb:10.5
      variables:
        MARIADB_ROOT_PASSWORD: test
  caches:
    npm: $HOME/.npm

pipelines:
  default:
    - parallel:
        steps:
          - step:
              <<: *base
              name: PHP Lint
              script:
                - *baseInstallDeps
                - *baseInst
                - moodle-plugin-ci phplint
          - step:
              <<: *base
              name: PHP CPD
              script:
                - *baseInstallDeps
                - *baseInst
                - moodle-plugin-ci phpcpd
          - step:
              <<: *base
              name: PHP MD
              script:
                - *baseInstallDeps
                - *baseInst
                - moodle-plugin-ci phpmd
          - step:
              <<: *base
              name: Code checker
              script:
                - *baseInstallDeps
                - *baseInst
                - moodle-plugin-ci codechecker
          - step:
              <<: *base
              name: Validate
              script:
                - *baseInstallDeps
                - *baseInst
                - moodle-plugin-ci validate
          - step:
              <<: *base
              name: Savepoints
              script:
                - *baseInstallDeps
                - *baseInst
                - moodle-plugin-ci savepoints
          - step:
              <<: *base
              name: Mustache
              script:
                - *baseInstallDeps
                - *baseInst
                - moodle-plugin-ci mustache
          - step:
              <<: *base
              name: Grunt
              script:
                - *baseInstallDeps
                - *baseInst
                - moodle-plugin-ci grunt
          - step:
              <<: *base
              name: PHP Doc
              script:
                - *baseInstallDeps
                - *baseInst
                - moodle-plugin-ci phpdoc
          - step:
              <<: *base
              name: PHP Unit
              script:
                - *baseInstallDeps
                - *baseInst
                - moodle-plugin-ci phpunit
          - step:
              <<: *base
              name: Behat
              script:
                - *baseInstallDeps
                - *baseInst
                - *baseBehat
                - moodle-plugin-ci behat
