---
image:
  name: '271411534863.dkr.ecr.us-east-2.amazonaws.com/moodleusdev:latest'
  aws:
    access-key: "$AWS_ACCESS_KEY"
    secret-key: "$AWS_SECRET_KEY"
definitions:
  .install-401: &install401
      setphpversion 8.1 ;
      moodle-plugin-ci -vvv install --no-init --branch="MOODLE_401_STABLE" --repo="$REPOSITORY" ;
  .install-402: &install402
      setphpversion 8.1 ;
      moodle-plugin-ci -vvv install --no-init --branch="MOODLE_402_STABLE" --repo="$REPOSITORY" ;
  .install-403: &install403
      setphpversion 8.1 ;
      moodle-plugin-ci -vvv install --no-init --branch="MOODLE_403_STABLE" --repo="$REPOSITORY" ;
  .install-404: &install404
      setphpversion 8.1 ;
      moodle-plugin-ci -vvv install --no-init --branch="MOODLE_404_STABLE" --repo="$REPOSITORY" ;
  .install-405: &install405
      setphpversion 8.1 ;
      moodle-plugin-ci -vvv install --no-init --branch="MOODLE_405_STABLE" --repo="$REPOSITORY" ;
  .install-401: &install401full
      setphpversion 8.1 ;
      moodle-plugin-ci -vvv install --branch="MOODLE_401_STABLE" --repo="$REPOSITORY" ;
  .install-402: &install402full
      setphpversion 8.1 ;
      moodle-plugin-ci -vvv install --branch="MOODLE_402_STABLE" --repo="$REPOSITORY" ;
  .install-403: &install403full
      setphpversion 8.1 ;
      moodle-plugin-ci -vvv install --branch="MOODLE_403_STABLE" --repo="$REPOSITORY" ;
  .install-404: &install404full
      setphpversion 8.1 ;
      moodle-plugin-ci -vvv install --branch="MOODLE_404_STABLE" --repo="$REPOSITORY" ;
  .install-405: &install405full
      setphpversion 8.1 ;
      moodle-plugin-ci -vvv install --branch="MOODLE_405_STABLE" --repo="$REPOSITORY" ;
  steps:
    - step: &base
        name: 'Set up Docker, Composer and MariaDB 10.6'
        caches:
          - npm
          - composer
        services:
          - mariadb
  services:
    mariadb:
      image: mariadb:10.6
      variables:
        MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: 'yes'
  caches:
    npm:
      path: $HOME/.npm
pipelines:
  default:
    - parallel:
        steps:
          # Moodle 4.1
          - step:
              <<: *base
              name: PHP Lint 4.1
              script:
                - *install401
                - moodle-plugin-ci phplint
          - step:
              <<: *base
              name: PHP Copy detector 4.1
              script:
                - *install401
                - moodle-plugin-ci phpcpd
          - step:
              <<: *base
              name: PHP Mess detector 4.1
              script:
                - *install401
                - moodle-plugin-ci phpmd
          - step:
              <<: *base
              name: PHP Code checker 4.1
              script:
                - *install401
                - moodle-plugin-ci codechecker
          - step:
              <<: *base
              name: PHP Validate 4.1
              script:
                - *install401
                - moodle-plugin-ci validate
          - step:
              <<: *base
              name: PHP Savepoints 4.1
              script:
                - *install401
                - moodle-plugin-ci savepoints
          - step:
              <<: *base
              name: PHP Mustache 4.1
              script:
                - *install401
                - moodle-plugin-ci mustache
          - step:
              <<: *base
              name: PHP Grunt 4.1
              script:
                - *install401
                - moodle-plugin-ci grunt
          - step:
              <<: *base
              name: PHP Doc 4.1
              script:
                - *install401
                - moodle-plugin-ci phpdoc
          - step:
              <<: *base
              name: PHPUnit 4.1
              script:
                - *install401full
                - moodle-plugin-ci phpunit
          - step:
              <<: *base
              name: PHP Deprecations 4.1
              script:
                - *install401
                - moodle-plugin-ci codechecker --standard=/usr/local/mds --max-warnings=1
          # Moodle 4.2
          - step:
              <<: *base
              name: PHP Lint 4.2
              script:
                - *install402
                - moodle-plugin-ci phplint
          - step:
              <<: *base
              name: PHP Copy detector 4.2
              script:
                - *install402
                - moodle-plugin-ci phpcpd
          - step:
              <<: *base
              name: PHP Mess detector 4.2
              script:
                - *install402
                - moodle-plugin-ci phpmd
          - step:
              <<: *base
              name: PHP Code checker 4.2
              script:
                - *install402
                - moodle-plugin-ci codechecker
          - step:
              <<: *base
              name: PHP Validate 4.2
              script:
                - *install402
                - moodle-plugin-ci validate
          - step:
              <<: *base
              name: PHP Savepoints 4.2
              script:
                - *install402
                - moodle-plugin-ci savepoints
          - step:
              <<: *base
              name: PHP Mustache 4.2
              script:
                - *install402
                - moodle-plugin-ci mustache
          - step:
              <<: *base
              name: PHP Grunt 4.2
              script:
                - *install402
                - moodle-plugin-ci grunt
          - step:
              <<: *base
              name: PHP Doc 4.2
              script:
                - *install402
                - moodle-plugin-ci phpdoc
          - step:
              <<: *base
              name: PHPUnit 4.2
              script:
                - *install402full
                - moodle-plugin-ci phpunit
          - step:
              <<: *base
              name: PHP Deprecations 4.2
              script:
                - *install402
                - moodle-plugin-ci codechecker --standard=/usr/local/mds --max-warnings=1
          # Moodle 4.3
          - step:
              <<: *base
              name: PHP Lint 4.3
              script:
                - *install403
                - moodle-plugin-ci phplint
          - step:
              <<: *base
              name: PHP Copy detector 4.3
              script:
                - *install403
                - moodle-plugin-ci phpcpd
          - step:
              <<: *base
              name: PHP Mess detector 4.3
              script:
                - *install403
                - moodle-plugin-ci phpmd
          - step:
              <<: *base
              name: PHP Code checker 4.3
              script:
                - *install403
                - moodle-plugin-ci codechecker
          - step:
              <<: *base
              name: PHP Validate 4.3
              script:
                - *install403
                - moodle-plugin-ci validate
          - step:
              <<: *base
              name: PHP Savepoints 4.3
              script:
                - *install403
                - moodle-plugin-ci savepoints
          - step:
              <<: *base
              name: PHP Mustache 4.3
              script:
                - *install403
                - moodle-plugin-ci mustache
          - step:
              <<: *base
              name: PHP Grunt 4.3
              script:
                - *install403
                - moodle-plugin-ci grunt
          - step:
              <<: *base
              name: PHP Doc 4.3
              script:
                - *install403
                - moodle-plugin-ci phpdoc
          - step:
              <<: *base
              name: PHPUnit 4.3
              script:
                - *install403full
                - moodle-plugin-ci phpunit
          - step:
              <<: *base
              name: PHP Deprecations 4.3
              script:
                - *install403
                - moodle-plugin-ci codechecker --standard=/usr/local/mds --max-warnings=1
          # Moodle 4.4
          - step:
              <<: *base
              name: PHP Lint 4.4
              script:
                - *install404
                - moodle-plugin-ci phplint
          - step:
              <<: *base
              name: PHP Copy detector 4.4
              script:
                - *install404
                - moodle-plugin-ci phpcpd
          - step:
              <<: *base
              name: PHP Mess detector 4.4
              script:
                - *install404
                - moodle-plugin-ci phpmd
          - step:
              <<: *base
              name: PHP Code checker 4.4
              script:
                - *install404
                - moodle-plugin-ci codechecker
          - step:
              <<: *base
              name: PHP Validate 4.4
              script:
                - *install404
                - moodle-plugin-ci validate
          - step:
              <<: *base
              name: PHP Savepoints 4.4
              script:
                - *install404
                - moodle-plugin-ci savepoints
          - step:
              <<: *base
              name: PHP Mustache 4.4
              script:
                - *install404
                - moodle-plugin-ci mustache
          - step:
              <<: *base
              name: PHP Grunt 4.4
              script:
                - *install404
                - moodle-plugin-ci grunt
          - step:
              <<: *base
              name: PHP Doc 4.4
              script:
                - *install404
                - moodle-plugin-ci phpdoc
          - step:
              <<: *base
              name: PHPUnit 4.4
              script:
                - *install404full
                - moodle-plugin-ci phpunit
          - step:
              <<: *base
              name: PHP Deprecations 4.4
              script:
                - *install404
                - moodle-plugin-ci codechecker --standard=/usr/local/mds --max-warnings=1
          # Moodle 4.5
          - step:
              <<: *base
              name: PHP Lint 4.5
              script:
                - *install405
                - moodle-plugin-ci phplint
          - step:
              <<: *base
              name: PHP Copy detector 4.5
              script:
                - *install405
                - moodle-plugin-ci phpcpd
          - step:
              <<: *base
              name: PHP Mess detector 4.5
              script:
                - *install405
                - moodle-plugin-ci phpmd
          - step:
              <<: *base
              name: PHP Code checker 4.5
              script:
                - *install405
                - moodle-plugin-ci codechecker
          - step:
              <<: *base
              name: PHP Validate 4.5
              script:
                - *install405
                - moodle-plugin-ci validate
          - step:
              <<: *base
              name: PHP Savepoints 4.5
              script:
                - *install405
                - moodle-plugin-ci savepoints
          - step:
              <<: *base
              name: PHP Mustache 4.5
              script:
                - *install405
                - moodle-plugin-ci mustache
          - step:
              <<: *base
              name: PHP Grunt 4.5
              script:
                - *install405
                - moodle-plugin-ci grunt
          - step:
              <<: *base
              name: PHP Doc 4.5
              script:
                - *install405
                - moodle-plugin-ci phpdoc
          - step:
              <<: *base
              name: PHPUnit 4.5
              script:
                - *install405full
                - moodle-plugin-ci phpunit
          - step:
              <<: *base
              name: PHP Deprecations 4.5
              script:
                - *install405
                - moodle-plugin-ci codechecker --standard=/usr/local/mds --max-warnings=1
