---
image:
  name: '271411534863.dkr.ecr.us-east-2.amazonaws.com/moodleusdev:latest'
  aws:
    access-key: "$AWS_ACCESS_KEY"
    secret-key: "$AWS_SECRET_KEY"
definitions:
  installscript: &baseInst
    echo "Checking out Moodle Workplace\n" ;
    moodle-plugin-ci install --branch='MOODLE_401_STABLE' ;
  steps:
    - step: &maridb
        name: 'Moodle 4.1, PHP 7.4 and MariaDB 10.6'
        caches:
          - npm
          - composer
          - docker
        services:
          - mariadb
          - docker
    - step: &mysql
        name: 'Moodle 4.1, PHP 7.4 and MySQL 5.7'
        caches:
          - npm
          - composer
          - docker
        services:
          - mysql
          - docker
    - step: &postgres
        name: 'Moodle 4.1, PHP 7.4 and PostgreSQL 13'
        caches:
          - npm
          - composer
          - docker
        services:
          - postgres
          - docker
  services:
    mariadb:
      image: mariadb:10.6
      variables:
        MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: 'yes'
    mysql:
      image: 'mysql:5.7'
      variables:
        MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    postgres:
      image: 'postgres:13'
      variables:
        POSTGRES_USER: 'postgres'
        POSTGRES_HOST_AUTH_METHOD: 'trust'

  caches:
    npm: $HOME/.npm
pipelines:
  default:
    - parallel:
        steps:
          - step:
              <<: *maridb
              name: PHP Lint
              script:
                - *baseInst
                - moodle-plugin-ci phplint
          - step:
              <<: *maridb
              name: PHP Copy detector 
              script:
                - *baseInst
                - moodle-plugin-ci phpcpd
          - step:
              <<: *maridb
              name: PHP Mess detector
              script:
                - *baseInst
                - moodle-plugin-ci phpmd
          - step:
              <<: *maridb
              name: PHP Code checker
              script:
                - *baseInst
                - moodle-plugin-ci codechecker
          - step:
              <<: *maridb
              name: PHP Validate
              script:
                - *baseInst
                - moodle-plugin-ci validate
          - step:
              <<: *maridb
              name: PHP Savepoints
              script:
                - *baseInst
                - moodle-plugin-ci savepoints
          - step:
              <<: *maridb
              name: PHP Mustache
              script:
                - *baseInst
                - moodle-plugin-ci mustache
          - step:
              <<: *maridb
              name: PHP Grunt
              script:
                - *baseInst
                - moodle-plugin-ci grunt
          - step:
              <<: *maridb
              name: PHP Doc
              script:
                - *baseInst
                - moodle-plugin-ci phpdoc
          - step:
              <<: *maridb
              name: PHPUnit
              script:
                - *baseInst
                - moodle-plugin-ci phpunit
          - step:
              <<: *mysql
              name: PHP Savepoints mysql
              script:
                - *baseInst
                - moodle-plugin-ci savepoints
          - step:
              <<: *mysql
              name: PHPUnit mysql
              script:
                - *baseInst
                - moodle-plugin-ci phpunit
          - step:
              <<: *postgres
              name: PHP Savepoints postgres
              script:
                - *baseInst
                - moodle-plugin-ci savepoints
          - step:
              <<: *postgres
              name: PHPUnit postgres
              script:
                - *baseInst
                - moodle-plugin-ci phpunit