# Start of the yml file

image:
  name: '271411534863.dkr.ecr.us-east-2.amazonaws.com/moodleusdev:latest'
  aws:
    access-key: "$AWS_ACCESS_KEY"
    secret-key: "$AWS_SECRET_KEY"
definitions:
  services:
    mariadb:
      image: mariadb:10
      variables:
        MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: 'yes'
  caches:
    npm: $HOME/.npm
pipelines:
  default:
    - step:
        name: 'Moodle 3.11, PHP 7.4 and MariaDB 10'
        services:
          - mariadb
        caches:
          - npm
          - composer
        script:
          - moodle-plugin-ci install --branch='MOODLE_311_STABLE'
          - moodle-plugin-ci phplint
          - moodle-plugin-ci phpcpd
          - moodle-plugin-ci phpmd
          - moodle-plugin-ci codechecker
          - moodle-plugin-ci validate
          - moodle-plugin-ci savepoints
          - moodle-plugin-ci mustache
          - moodle-plugin-ci grunt
          - moodle-plugin-ci phpdoc
          - moodle-plugin-ci phpunit
